### PR TITLE
Fix AttributeError: 'Authorization' object has no attribute 'log'

### PR DESCRIPTION
**Pull request by MetRonnie**
Edit: fixes a bug introduced in #613 

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Tests are included (or explain why tests are not needed).
- [x] Changelog entry included if this is a change that can affect users
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by wxtim** [comment]
Please can you paste what you did to demonstrate the bug?

File: cylc/uiserver/authorise.py [hunk 1]
```diff
@@ -165,12 +165,12 @@ def __init__(
...
         self.owner_user_name: str = owner_user_name
-        self.owner_user_groups: List[str] = self._get_groups(
-            self.owner_user_name
-        )
         self.log = log
         self.owner_auth_conf: dict = owner_auth_conf
         self.site_auth_config: dict = site_auth_conf
+        self.owner_user_groups: List[str] = self._get_groups(
+            self.owner_user_name
+        )
```
Comment (MetRonnie) [inline cylc/uiserver/authorise.py:173]: I don't know how to reproduce it, but the cause should be fairly self-evident from looking at `self._get_groups()`:
https://github.com/cylc/cylc-uiserver/blob/ef4a4d1ec613dec6aba6e6446f530fbf285659d4/cylc/uiserver/authorise.py#L487-L492

Can't use `self.log` before it's been defined

**Review by wxtim — APPROVED** [review]
👍🏼
